---
- hosts: all

  become: true
  tasks:
    - name: Add the user with 'username' and ad them to different groups
      ansible.builtin.user:
        name: {{ username }}
        shell: /bin/bash
        create_home: yes
        groups: adm,cdrom,sudo,dip,lxd
        append: yes
    - name: make sure sudo works without password
        copy:
          dest: /etc/sudoers.d/dont-prompt-ubuntu_user-for-sudo-password
          content: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
    - name: Set authorized key for user codasys copying it from local file
      ansible.posix.authorized_key:
        user: {{ username }}
        state: present
        key: "{{ lookup('file', '/config/.ssh/authorized_keys') }}"
